spring:
  application:
    name: spring-data-redis
  redis:
    host: localhost
    database: 1
  boot:
    admin:
      client:
        url: http://localhost:9090/

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    instance:
    preferIpAddress: true